03 1
chie-id/repo2 pull request #8
Opened 2023-06-14 13:53 UTC by chie-id

!

2023-06-14 13:55 UTC, chie-id reviewed
!

2023-06-14 14:51 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応ください！

2023-06-14 14:51 UTC, MasatoshiMizumoto commented on folder03/lecture03.1.md
>  ### ●サンプルアプリケーション(Roby on Rails)を起動してブラウザで表示させる
これは見出しより番号無しリストにしたほうがよくないですかね？？
見出しにするなら入れる以上、本文がないのはおかしくなっちゃいますので。
目次作ったときに中身ない章ができちゃいます。

```suggestion
- cloud9に『APサーバー』と『DBサーバー』をインストールする
- サンプルアプリケーション(Roby on Rails)を起動してブラウザで表示させる
```

2023-06-14 14:51 UTC, MasatoshiMizumoto commented on folder03/lecture03.1.md
>  ### 2.GitHub上のサンプルアプリケーションをcloud9にクローンする
ここは番号つきリストでよさそうかなと思います！
```suggestion
1. cloud9に課題用の環境を作成する
2. GitHub上のサンプルアプリケーションをcloud9にクローンする

```

2023-06-15 00:45 UTC, MasatoshiMizumoto approved these changes
OKですがコメントした部分の内容を反映してからマージしておいてください！

2023-06-15 00:45 UTC, MasatoshiMizumoto commented on folder03/lecture03.1.md
>  - コマンド：bunble install など
typoしてますね！
他にもあるぽいので全部直しておいてください！

2023-06-15 12:27 UTC, chie-id commented
!

2023-06-15 12:28 UTC, merged